### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by larsjanssen6** [blastcloud/guzzler#10]
Hi,

Great package :)

I'm using guzzler package in one of my Laravel applications (first time). 

And my test looks like this:

```
$this->guzzler->expects($this->exactly(1))
    ->get("/customerrssss")
    ->willRespond(
        new Response(
            201,
            [],
            '{ "test": "test" }'
        ));

$client = $this->guzzler->getClient([
    "base_uri" => "https://api.mollie.com/v2/"
]);

$apiClient = new MollieApiClient($client);

$apiClient->setApiKey('test_dHar4XY7LxsDOtmnkVtjNVWXLSlXsM');

Mollie::shouldReceive('api')
    ->once()
    ->andReturn(new MollieApiWrapper($this->app['config'], $apiClient));

$response = $this->post('/api/register', [
    'city' => 'Den Bosch',
]);

dd($response);
```

The response is `'{ "test": "test" }'`. But I don't use the
url `/customerrssss` but `/customers` in my controller. 

So it looks like it doesn't matter what url I provide I always get that response. What 
could I be doing wrong here ?

Thanks!

**Comment by adamkelso** [comment]
Hey @larsjanssen6 . Thanks! I’m glad you’re enjoying the package. A couple things:

1. What Mollie package are you using?
2. Without recreating everything, my guess is that you might have missed the **Be Aware** notice that says whatever order you add responses to the queue is the order they will be returned. Internally, Guzzle’s mock queue is just an array of responses, and each request made in the mock just returns the next response in the array. Because of this, there is no way for me to determine which response you’d like returned. If that’s the case, I’m sorry it’s a little confusing.

Also, if you’re surprised that an error is not thrown in the test, that is probably because you are `dd()`ing the results before the test ends. Guzzler checks all your `Expectation`s in a method marked with the annotation `@after`, so the check runs between your test method and any `tearDown()` method you might have.

**Comment by adamkelso** [comment]
@larsjanssen6 Just checking in to see if your question was answered.

**Comment by larsjanssen6** [comment]
@adamkelso hey! sorry for the late reaction. Yes I've got it working now. Turns out to be easier then I thought :) Thanks for your support and of course this package!

**Comment by adamkelso** [comment]
@larsjanssen6 Glad to hear, and Happy to help. :)
