### ISSUE TITLE
JSON-RPC 2.0 mock

### ISSUE THREAD

**Issue by webdevium** [blastcloud/guzzler#12]
Quite often we need to mock RPC requests.

We can easily create a macro:

```
Expectation::macro('withJsonRpc', function (Expectation $e, $endpoint, $method, $params, $id = null) {

    $json = [
        'jsonrpc' => "2.0",
        'method' => $method,
        'params' => $params,
    ];

    if ($id) {
        $json['id'] = $id;
    }

    return $e
        ->post($endpoint)
        ->withJson($json);
});
```

But, unfortunately, if we get an exception, then we cannot understand that it was exactly a call of **withJsonRpc()**

How about creating a separate filter with own error message? Something like

```
JSON-RPC
Endpoint: /rpc
Method:   POST
Body: {
    "id": 123,
    "jsonrpc": "2.0",
    "method": "test-method",
    "params": {
        "a": 1,
        "b": 2
    }
}
```

**Comment by adamkelso** [comment]
Hey @webdevium 

Thanks! That's a great idea. Would you like to create a pull request, or would you prefer I come up with an option?

**Comment by adamkelso** [comment]
@webdevium So, this kind of shows it's been a long time since I've updated the code in this project. But there is a third argument you can pass into the definition of the macro - after the closure - where you can pass a message string that is shown when the macro fails. It appears this argument is not shown in the documentation, so apologies for that. I'll update the docs to make that explicit.

Would this be adequate, or is there more functionality you'd need?
